-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 19:51:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shipment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shipment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shipment` DEFAULT CHARACTER SET utf8 ;
USE `shipment` ;

-- -----------------------------------------------------
-- Table `shipment`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`customer` ;

CREATE TABLE IF NOT EXISTS `shipment`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `phone_num` DECIMAL(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipment`.`shipper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`shipper` ;

CREATE TABLE IF NOT EXISTS `shipment`.`shipper` (
  `shipper_id` INT NOT NULL,
  `email_address` VARCHAR(70) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`shipper_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipment`.`collector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`collector` ;

CREATE TABLE IF NOT EXISTS `shipment`.`collector` (
  `collector_id` INT NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(70) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`collector_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipment`.`shipping_booking_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`shipping_booking_request` ;

CREATE TABLE IF NOT EXISTS `shipment`.`shipping_booking_request` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `box_num` INT NOT NULL,
  `destination_address` VARCHAR(70) NOT NULL,
  `pickup_address` VARCHAR(70) NOT NULL,
  `departure_date` DATETIME NOT NULL,
  `arrival_date` DATETIME NOT NULL,
  `message` MEDIUMTEXT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_ShippingBookingRequest_Customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_ShippingBookingRequest_Customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `shipment`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipment`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`status` ;

CREATE TABLE IF NOT EXISTS `shipment`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shipment`.`shipping_booking_ack`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shipment`.`shipping_booking_ack` ;

CREATE TABLE IF NOT EXISTS `shipment`.`shipping_booking_ack` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `status_id` INT NOT NULL,
  `pickupTime` INT NULL,
  `message` MEDIUMTEXT NULL,
  `hbl_num` INT NULL,
  `collector_id` INT NOT NULL,
  `shipper_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `status_id_idx` (`status_id` ASC),
  INDEX `shipper_id_idx` (`shipper_id` ASC),
  INDEX `collector_id_idx` (`collector_id` ASC),
  CONSTRAINT `booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `shipment`.`shipping_booking_request` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `shipment`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `shipper_id`
    FOREIGN KEY (`shipper_id`)
    REFERENCES `shipment`.`shipper` (`shipper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `collector_id`
    FOREIGN KEY (`collector_id`)
    REFERENCES `shipment`.`collector` (`collector_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
